DoodleApp/DoodleApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('Doodlers.urls')),
	url(r'^index/', include('Doodlers.urls', namespace="Doodlers")),
    url(r'^admin/', include(admin.site.urls)),
]

DoodleApp/Doodlers/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^^Doodlers/$', views.IndexView, name='index'),
    url(r'^Doodlers/doodle/(?P<id>[0-9]+)/$', views.DoodleView, name='doodle'),
    url(r'^Doodlers/comment/(?P<id>[0-9]+)/$', views.comment, name='comment'),
]

call911/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]

DoodleApp/Doodlers/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.utils import timezone
import datetime
class Doodle(models.Model):
	title = models.CharField(max_length=75)
	pub_date = models.DateTimeField('date published')
	#image = models.ImageField(upload_to='images/',default = 'images/no-img.png')
	#user = models.ForeignKey(MyUser, unique=True)
	def __unicode__(self):
		return self.doodle
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
class Comment(models.Model):
	doodle = models.ForeignKey(Doodle)
	comment_text = models.TextField(max_length=500)
	pub_date = models.DateTimeField('date published')
	#votes = models.IntegerField(default=0)
	def __unicode__(self):
		return self.comment
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
class MyUserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=MyUserManager.normalize_email(email),
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, date_of_birth, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        u = self.create_user(username,
                        password=password,
                        date_of_birth=date_of_birth
                    )
        u.is_admin = True
        u.save(using=self._db)
        return u
class MyUser(AbstractBaseUser):
    email = models.EmailField(
                        verbose_name='email address',
                        max_length=255,
                        unique=True,
                    )
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __unicode__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

DoodleApp/Doodlers/views.py
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext, loader
from django.http import HttpResponse, HttpResponseRedirect
from Doodlers.models import Doodle, Comment
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from os.path import join as pjoin
import sentiment

# Create your views here.
class IndexView(generic.ListView):
	model = Doodle
	template_name = 'Doodlers/index.html'
	context_object_name = 'latest_doodles'
	def get_queryset(self):
		return Doodle.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
def DoodleView(request, id):
    response = "This is where %s doodle goes. Expect to see comments here" % Doodle.objects.get(pk=id).title
    template = loader.get_template('Doodlers/doodle.html')
    current_doodle = Doodle.objects.get(pk=id);
    comments = current_doodle.comment_set.all()
    scores = {}
    num_bad = 0
    for comment in comments:
            scores[comment.id] = sentiment.getSentiment(comment.comment_text)
            if scores[comment.id] < 0:
                    num_bad += 1

    context = RequestContext(request, {
            'doodle': current_doodle,
            'comments': comments,
            'scores': scores,
            'num_bad': num_bad,
    })
    return render(request, 'Doodlers/doodle.html', context)
def comment(request, id):
	doodle = get_object_or_404(Doodle, pk=id)
	print request.POST
	comment_text = request.POST.get('comment_text', False);
	if not comment_text:
		raise Exception('Whoa no comment text!')

	doodle.comment_set.create(comment_text=comment_text, pub_date=timezone.now())
	return HttpResponseRedirect(reverse('Doodler:DoodleView', args=(id))) 
def upload_picture(request, id):
	p = get_object_or_404(Doodle, pk=id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'Doodlers/detail.html', {
				'doodle': p,
				'error_message': "You didn't select a choice",
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
 		return HttpResponseRedirect(reverse('doodle:results', args=(p.id,))) 

DoodleApp/Doodlers/templates/Doodlers/comment.html
{% load staticfiles %}
<script src="{{ STATIC_URL }}Doodlers/jquery-1.11.3.min.js"></script>
<script src="{{ STATIC_URL }}Doodlers/jquery-migrate-1.2.1.min.js"></script>
<script src="{{ STATIC_URL }}Doodlers/underscore.js"></script>
<script src="{{ STATIC_URL }}Doodlers/backbone.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<link href="http://getbootstrap.com/examples/cover/cover.css" rel="stylesheet">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


<a>{{ comment }}</a>

DoodleApp/Doodlers/templates/Doodlers/doodle.html
{% load staticfiles %}
<script src="/static/Doodlers/jquery-1.11.3.min.js"></script>
<script src="/static/Doodlers/jquery-migrate-1.2.1.min.js"></script>
<script src="/static/Doodlers/underscore.js"></script>
<script src="/static/Doodlers/backbone.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<link href="http://getbootstrap.com/examples/cover/cover.css" rel="stylesheet">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<h1>{{doodle.title}}</h1>

<form action="{% url 'Doodlers:comment' doodle.id %}" method="post">
	{% csrf_token %}
	<textarea class="form-control" name="comment_text" form="usrform">
	</textarea>
	<input type="submit" value="Comment">
</form>

<ol>
{% for comment in comments %}
	{% for key, score in scores.items %}
		{% if key == comment.id and score > 0%}
		<li>
			{{comment.comment_text}} 
		</li>
    	{% endif %}
    {% endfor %}
{% endfor %}
{% if num_bad > 0 %}
	<li>
		{{num_bad}} comment(s) have been removed for potentially bad behavior
	<li>
{% endif %}
</ol>

DoodleApp/Doodlers/templates/Doodlers/index.html
{% load staticfiles %}
<script src="{{ STATIC_URL }}Doodlers/jquery-1.11.3.min.js"></script>
<script src="{{ STATIC_URL }}Doodlers/jquery-migrate-1.2.1.min.js"></script>
<script src="{{ STATIC_URL }}Doodlers/underscore.js"></script>
<script src="{{ STATIC_URL }}Doodlers/backbone.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<link href="http://getbootstrap.com/examples/cover/cover.css" rel="stylesheet">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<form role="form"  method="post">
    <div class="row">
        <div class="col-sm-6" id="search_container">
            <h3> Submit! </h3>
        </div>
        <div class="col-sm-6" id="search_container">
            <div class="form-group">
                <input type="file" name="pic" accept="image/*">
            </div>
        </div>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-info" value="Vote">
    </div>
</form>
{% if latest_doodles %}
    <ul>
    {% for doodle in latest_doodles %}
        <li><a href="/Doodlers/doodle/{{ doodle.id }}/">{{ doodle.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Doodles are available.</p>
{% endif %}